version: '2'
services:
  dj-perl:
    build:
      context: .
    image: 'theraccoonbear/dj-perl'
    environment:
      - APP_NAME=${APP_NAME}
      - APP_DB_NAME=${APP_DB_NAME}
      - APP_DB_USER=${APP_DB_USER}
      - APP_DB_PASSWORD=${APP_DB_PASSWORD}
      - APP_DB_HOST=${APP_DB_HOST}
      - APP_DB_PORT=${APP_DB_PORT}
      - DANCER_ENVIRONMENT=development
    hostname: dj-perl
    container_name: 'dj-perl'
    ports:
      - '5000:5000'
    volumes:
      - './:/opt/src'
    networks:
      - app
    links:
      - dj-postgres
    entrypoint: /opt/src/build/wait-and-start.sh

  dj-postgres:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - APP_DB_NAME=${APP_DB_NAME}
      - APP_DB_USER=${APP_DB_USER}
      - APP_DB_PASSWORD=${APP_DB_PASSWORD}
    ports:
      - '5432:5432'
    image: 'postgres:latest'
    container_name: 'dj-postgres'
    hostname: dj-postgres
    volumes:
      - './build/pg/postgres-init:/docker-entrypoint-initdb.d'
      - './build/pg/sql-scripts:/sql-scripts'
    networks:
      - app

networks:
  default:
    driver: bridge
  app:
    driver: bridge
