version: '2'
services:
  dj-perl:
    build:
      context: .
    image: 'theraccoonbear/dj-perl'
    environment:
      - DBNAME=double-jeopardy
      - DBUSER=postgres
      - DBPASS=qwerty1234
      - DBHOST=postgres
      - DBPORT=5432
      - PGUSER=postgres
      - PGPASS=qwerty1234
    hostname: dj-perl
    container_name: 'dj-perl'
    ports:
      - '5000:5000'
    volumes:
      - './:/opt/src'
    networks:
      - app
    links:
      - dj-postgres
    entrypoint: /opt/src/build/wait-and-start.sh

  dj-postgres:
    environment:
      - POSTGRES_PASSWORD=qwerty1234
    ports:
      - '5432:5432'
    image: 'postgres:latest'
    container_name: 'dj-postgres'
    networks:
      - app

networks:
  default:
    driver: bridge
  app:
    driver: bridge
