# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "hanglight"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "handlebars"

# template: "template_toolkit"
# engines:
#   template:
#     template_toolkit:
#       start_tag: '<%'
#       end_tag:   '%>'

# session engine
#
# Simple: in-memory session store - Dancer2::Session::Simple
# YAML: session stored in YAML files - Dancer2::Session::YAML
#
# Check out metacpan for other session storage options:
# https://metacpan.org/search?q=Dancer2%3A%3ASession&search_type=modules
#
# Default value for 'cookie_name' is 'dancer.session'. If you run multiple
# Dancer apps on the same host then you will need to make sure 'cookie_name'
# is different for each app.
#
#engines:
#  session:
#    Simple:
#      cookie_name: testapp.session
#
#engines:
#  session:
#    YAML:
#      cookie_name: eshop.session
#      is_secure: 1
#      is_http_only: 1

#session: MongoDB
template: "template_toolkit"

# "dbi:Pg:dbname=$ENV{APP_DB_NAME};host=$ENV{APP_DB_HOST}",
#   $ENV{APP_DB_USER},
#   $ENV{APP_DB_PASSWORD},

plugins:
  DBIC:
    default:
      dsn: dbi:Pg:dbname=hanglight;host=dj-postgres
      user: hanglight
      # @todo this has really got to be pulled from .env or something else, but this will work for local dev
      password: h4ngl!gh7
      schema_class: App::Schema


serializers:
  json: JSON

serializer: JSON

# @todo Dancer2::Session::DBIC

engines:
  # session:
  #   MongoDB:
  #     database_name: hanglight
  #     client_options:
  #       host: mongodb://hanglight-mongodb:27017
  template:
    template_toolkit:
      # start_tag: '<%'
      # encoding: '%>'
      show_private_variables: true
      plugins:
        json: 'Template::Plugin::JSON'
