#!/usr/bin/env bash

docker-compose -f docker-compose.yml up -d;
#docker-compose -f docker-compose.yml up;

NAME=$(grep hostname docker-compose.yml | head -1 | sed 's/.*:\s*//')

echo $NAME

docker logs -f $NAME;
